service: ec2-lab-2

frameworkVersion: ">=1.27.2 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  defaultStage: dev

provider:
  name: aws
  region: us-east-1
  runtime: nodejs6.10

functions:

resources:
  Resources:
    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: "Ec2DMZ"
        GroupDescription: "SSH HTTP HTTPS for DMZ"
        SecurityGroupIngress:
          - IpProtocol: "tcp"
            FromPort: 22
            ToPort: 22
            CidrIp: "0.0.0.0/0"
          - IpProtocol: "tcp"
            FromPort: 80
            ToPort: 80
            CidrIp: "0.0.0.0/0"
          - IpProtocol: "tcp"
            FromPort: 443
            ToPort: 443
            CidrIp: "0.0.0.0/0"
    Ec2Instance1:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: "ami-0080e4c5bc078760e" #Amazon Linux AMI HVM
        InstanceType: "t2.micro"
        KeyName: "MyEc2-Lab-Key" #setup key pair before deploy
        SecurityGroups:
          - Ref: "InstanceSecurityGroup"
          - "default"
        BlockDeviceMappings:
          - DeviceName: "/dev/xvda"
            Ebs:
              VolumeType: "gp2"
              DeleteOnTermination: "true"
              VolumeSize: "8"
          - DeviceName: "/dev/sdf"
            Ebs:
              VolumeType: "standard"
              DeleteOnTermination: "true"
              VolumeSize: "15"
        Tags:
          - Key: "Name"
            Value: "Ec2-Lab-2.1"
        UserData: ${file(scripts/ec2_startup.sh.base64)}
    Ec2Instance2:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: "ami-0080e4c5bc078760e" #Amazon Linux AMI HVM
        InstanceType: "t2.micro"
        KeyName: "MyEc2-Lab-Key" #setup key pair before deploy
        SecurityGroups:
          - Ref: "InstanceSecurityGroup"
          - "default"
        BlockDeviceMappings:
          - DeviceName: "/dev/xvda"
            Ebs:
              VolumeType: "gp2"
              DeleteOnTermination: "true"
              VolumeSize: "8"
          - DeviceName: "/dev/sdf"
            Ebs:
              VolumeType: "standard"
              DeleteOnTermination: "true"
              VolumeSize: "15"
        Tags:
          - Key: "Name"
            Value: "Ec2-Lab-2.2"
        UserData: ${file(scripts/ec2_startup.sh.base64)}
    ElasticLoadBalancer:
      Type: AWS::ElasticLoadBalancing::LoadBalancer
      Properties:
        CrossZone: "true"
        ConnectionDrainingPolicy:
          Enabled: "true"
          Timeout: "300"
        AvailabilityZones:
          Fn::GetAZs:
            Ref: "AWS::Region"
        Instances:
          - Ref: Ec2Instance1
          - Ref: Ec2Instance2
        Listeners:
          - LoadBalancerPort: "80"
            Protocol: "HTTP"
            InstancePort: "80"
            InstanceProtocol: "HTTP"
        HealthCheck:
          HealthyThreshold: "3"
          UnhealthyThreshold: "2"
          Interval: "10"
          Timeout: "5"
          Target:
            Fn::Join:
              - ""
              - - "HTTP:"
                - "80"
                - "/index.html"
        SecurityGroups:
          - Fn::GetAtt: [InstanceSecurityGroup, GroupId]
    FileSystem:
      Type: AWS::EFS::FileSystem
    MountTarget1:
      Type: AWS::EFS::MountTarget
      Properties:
        FileSystemId:
          Ref: "FileSystem"
        SubnetId: "xxxx" #look in VPC AWS Console and select a subnet
        SecurityGroups:
          - "xxxx" #id of default security group vpc
    MountTarget2:
      Type: AWS::EFS::MountTarget
      Properties:
        FileSystemId:
          Ref: "FileSystem"
        SubnetId: "xxxx" #look in VPC AWS Console and select a subnet
        SecurityGroups:
          - "xxxx" #id of default security group vpc

