service: ec2-lab-2

frameworkVersion: ">=1.27.2 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  defaultStage: dev

provider:
  name: aws
  region: us-east-1
  runtime: nodejs6.10

functions:

resources:
  Resources:
    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: "Ec2DMZ"
        GroupDescription: "SSH HTTP HTTPS for DMZ"
        SecurityGroupIngress:
          - IpProtocol: "tcp"
            FromPort: 22
            ToPort: 22
            CidrIp: "0.0.0.0/0"
          - IpProtocol: "tcp"
            FromPort: 80
            ToPort: 80
            CidrIp: "0.0.0.0/0"
          - IpProtocol: "tcp"
            FromPort: 443
            ToPort: 443
            CidrIp: "0.0.0.0/0"
    Volume:
      Type: AWS::EC2::Volume
      Properties:
        AvailabilityZone: { "Fn::GetAtt": ["Ec2Instance", "AvailabilityZone"] }
        Size: "10"
        VolumeType: "standard"
    Ec2Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: "ami-0080e4c5bc078760e" #Amazon Linux AMI HVM
        InstanceType: "t2.micro"
        KeyName: "MyEc2-Lab-Key" #setup key pair before deploy
        SecurityGroups:
          - Ref: "InstanceSecurityGroup" #!GetAtt InstanceSecurityGroup.GroupName (i think)
        Tags:
          - Key: "Name"
            Value: "Ec2-Lab-2"
        Volumes:
          - Device: "/dev/xvda"
            VolumeId: { "Ref": "Volume" }
